export type NewsCategory =
  | "india"
  | "world"
  | "politics"
  | "business"
  | "markets"
  | "technology"
  | "ai"
  | "cyber"
  | "science"
  | "space"
  | "health"
  | "environment"
  | "education"
  | "sports"
  | "entertainment";

export type SourceDefinition = {
  id: string;
  name: string;
  publisher: string;
  authority: string;

  kind: "rss" | "html";

  categories: NewsCategory[];

  region: "india" | "global" | "regional";

  trustTier: 1 | 2 | 3 | 4;
  dependencyGroup: string;

  url: string;
  siteUrl: string;
  allowedHosts: string[];

  strictFilter: boolean;

  /** Whether publisher-provided feed prose may be retained as a bounded summary. */
  feedSummaryPolicy?: "bounded" | "metadata-only";

  enabled: boolean;

  usage: "approved" | "review-required" | "restricted";
};

export type LegacyCertInDefinition = SourceDefinition & {
  identifierPrefix?: "CIAD" | "CIVN";
  detailPageId?: "PUBVLNOTES02" | "PUBVLNOTES01";
};

const CERT_IN_ORIGIN = "https://www.cert-in.org.in";

export function getSourceDefinitions(year: number): LegacyCertInDefinition[] {
  return [
    {
      id: "cert-in-advisories",
      name: "CERT-In Advisories",
      publisher: "CERT-In",
      authority: "Indian Computer Emergency Response Team (CERT-In), Government of India",
      kind: "html",
      categories: ["cyber", "technology", "india"],
      region: "india",
      trustTier: 1,
      dependencyGroup: "cert-in",
      url: `${CERT_IN_ORIGIN}/s2cMainServlet?pageid=PUBADVLIST02&year=${year}`,
      siteUrl: `${CERT_IN_ORIGIN}/`,
      allowedHosts: ["www.cert-in.org.in", "cert-in.org.in"],
      strictFilter: true,
      enabled: true,
      usage: "approved",
      identifierPrefix: "CIAD",
      detailPageId: "PUBVLNOTES02",
    },
    {
      id: "cert-in-vulnerability-notes",
      name: "CERT-In Vulnerability Notes",
      publisher: "CERT-In",
      authority: "Indian Computer Emergency Response Team (CERT-In), Government of India",
      kind: "html",
      categories: ["cyber", "technology", "india"],
      region: "india",
      trustTier: 1,
      dependencyGroup: "cert-in",
      url: `${CERT_IN_ORIGIN}/s2cMainServlet?pageid=VLNLIST02&year=${year}`,
      siteUrl: `${CERT_IN_ORIGIN}/`,
      allowedHosts: ["www.cert-in.org.in", "cert-in.org.in"],
      strictFilter: true,
      enabled: true,
      usage: "approved",
      identifierPrefix: "CIVN",
      detailPageId: "PUBVLNOTES01",
    },
    {
      id: "et-ciso-news",
      name: "ET CISO News",
      publisher: "ET CISO",
      authority: "Economic Times CISO, Times Group, India",
      kind: "rss",
      categories: ["cyber", "technology", "business", "india"],
      region: "india",
      trustTier: 2,
      dependencyGroup: "times-group-et-ciso",
      url: "https://ciso.economictimes.indiatimes.com/rss/recentstories",
      siteUrl: "https://ciso.economictimes.indiatimes.com/",
      allowedHosts: ["ciso.economictimes.indiatimes.com"],
      strictFilter: true,
      enabled: true,
      usage: "approved",
    },
    {
      id: "the-hacker-news",
      name: "The Hacker News",
      publisher: "The Hacker News",
      authority: "THN Media Private Limited, India",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "thn-media",
      url: "https://feeds.feedburner.com/TheHackersNews",
      siteUrl: "https://thehackernews.com/",
      allowedHosts: ["thehackernews.com", "www.thehackernews.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "seqrite-research",
      name: "Seqrite Labs Research",
      publisher: "Seqrite Labs",
      authority: "Seqrite / Quick Heal Technologies, India",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "quick-heal-seqrite",
      url: "https://www.seqrite.com/blog/feed/",
      siteUrl: "https://www.seqrite.com/blog/",
      allowedHosts: ["www.seqrite.com", "seqrite.com"],
      strictFilter: true,
      enabled: true,
      usage: "approved",
    },
    {
      id: "cloudsek-intelligence",
      name: "CloudSEK Threat Intelligence",
      publisher: "CloudSEK",
      authority: "CloudSEK threat-intelligence research",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "cloudsek",
      url: "https://www.cloudsek.com/blog/rss.xml",
      siteUrl: "https://www.cloudsek.com/blog",
      allowedHosts: ["www.cloudsek.com", "cloudsek.com"],
      strictFilter: true,
      enabled: true,
      usage: "approved",
    },
    {
      id: "microsoft-security-blog",
      name: "Microsoft Security Blog",
      publisher: "Microsoft Security",
      authority: "Microsoft Security official newsroom and research",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 1,
      dependencyGroup: "microsoft",
      url: "https://www.microsoft.com/en-us/security/blog/feed/",
      siteUrl: "https://www.microsoft.com/en-us/security/blog/",
      allowedHosts: ["www.microsoft.com", "microsoft.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "cisco-talos-research",
      name: "Cisco Talos Research",
      publisher: "Cisco Talos",
      authority: "Cisco Talos threat research",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "cisco-talos",
      url: "https://blog.talosintelligence.com/rss/",
      siteUrl: "https://blog.talosintelligence.com/",
      allowedHosts: ["blog.talosintelligence.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "eset-welivesecurity",
      name: "ESET WeLiveSecurity",
      publisher: "ESET WeLiveSecurity",
      authority: "ESET security research newsroom",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "eset",
      url: "https://www.welivesecurity.com/en/rss/feed/",
      siteUrl: "https://www.welivesecurity.com/en/",
      allowedHosts: ["www.welivesecurity.com", "welivesecurity.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "rbi-cyber-updates",
      name: "RBI Cyber & Digital Risk Updates",
      publisher: "Reserve Bank of India",
      authority: "Reserve Bank of India",
      kind: "rss",
      categories: ["cyber", "technology", "business", "india"],
      region: "india",
      trustTier: 1,
      dependencyGroup: "reserve-bank-of-india",
      url: "https://rbi.org.in/notifications_rss.xml",
      siteUrl: "https://www.rbi.org.in/",
      allowedHosts: ["rbi.org.in", "www.rbi.org.in"],
      strictFilter: true,
      enabled: true,
      usage: "approved",
    },
    {
      id: "sebi-cyber-updates",
      name: "SEBI Cyber & Market Security Updates",
      publisher: "SEBI",
      authority: "Securities and Exchange Board of India",
      kind: "rss",
      categories: ["cyber", "technology", "business", "markets", "india"],
      region: "india",
      trustTier: 1,
      dependencyGroup: "sebi",
      url: "https://www.sebi.gov.in/sebirss.xml",
      siteUrl: "https://www.sebi.gov.in/",
      allowedHosts: ["www.sebi.gov.in", "sebi.gov.in"],
      strictFilter: true,
      enabled: true,
      usage: "approved",
    },
    {
      id: "bleepingcomputer-news",
      name: "BleepingComputer",
      publisher: "BleepingComputer",
      authority: "BleepingComputer cybersecurity and technology news",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "bleepingcomputer",
      url: "https://www.bleepingcomputer.com/feed/",
      siteUrl: "https://www.bleepingcomputer.com/",
      allowedHosts: ["www.bleepingcomputer.com", "bleepingcomputer.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "krebs-on-security",
      name: "KrebsOnSecurity",
      publisher: "KrebsOnSecurity",
      authority: "Brian Krebs, independent investigative cybersecurity journalist",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "krebs-on-security",
      url: "https://krebsonsecurity.com/feed/",
      siteUrl: "https://krebsonsecurity.com/",
      allowedHosts: ["krebsonsecurity.com", "www.krebsonsecurity.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "google-tag-blog",
      name: "Google Threat Analysis Group",
      publisher: "Google TAG",
      authority: "Google Threat Analysis Group, Alphabet Inc.",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 1,
      dependencyGroup: "google",
      url: "https://blog.google/threat-analysis-group/rss/",
      siteUrl: "https://blog.google/threat-analysis-group/",
      allowedHosts: ["blog.google"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "kaspersky-securelist",
      name: "Kaspersky Securelist",
      publisher: "Kaspersky Securelist",
      authority: "Kaspersky Lab threat research and analysis",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "kaspersky",
      url: "https://securelist.com/feed/",
      siteUrl: "https://securelist.com/",
      allowedHosts: ["securelist.com", "www.securelist.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "dark-reading-news",
      name: "Dark Reading",
      publisher: "Dark Reading",
      authority: "Dark Reading, Informa TechTarget cybersecurity news",
      kind: "rss",
      categories: ["cyber", "technology"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "dark-reading",
      url: "https://www.darkreading.com/rss.xml",
      siteUrl: "https://www.darkreading.com/",
      allowedHosts: ["www.darkreading.com", "darkreading.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    // ---- BATCH A: INDIA ----
    {
      id: "pib-india",
      name: "Press Information Bureau",
      publisher: "PIB India",
      authority: "Press Information Bureau, Government of India",
      kind: "rss",
      categories: ["india", "politics", "business"],
      region: "india",
      trustTier: 1,
      dependencyGroup: "pib-india",
      url: "https://pib.gov.in/rss/Mainstream.xml",
      siteUrl: "https://pib.gov.in/",
      allowedHosts: ["pib.gov.in", "www.pib.gov.in"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "isro-news",
      name: "ISRO Updates",
      publisher: "ISRO",
      authority: "Indian Space Research Organisation",
      kind: "rss",
      categories: ["india", "science", "space"],
      region: "india",
      trustTier: 1,
      dependencyGroup: "isro",
      url: "https://www.isro.gov.in/rss.xml",
      siteUrl: "https://www.isro.gov.in/",
      allowedHosts: ["isro.gov.in", "www.isro.gov.in"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    // ---- BATCH A: WORLD ----
    {
      id: "sky-news-world",
      name: "Sky News World",
      publisher: "Sky News",
      authority: "Sky News UK",
      kind: "rss",
      categories: ["world", "politics"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "sky-news",
      url: "https://feeds.skynews.com/feeds/rss/world.xml",
      siteUrl: "https://news.sky.com/world",
      allowedHosts: ["news.sky.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "dw-news",
      name: "DW News",
      publisher: "Deutsche Welle",
      authority: "Deutsche Welle News",
      kind: "rss",
      categories: ["world", "politics", "business"],
      region: "global",
      trustTier: 1,
      dependencyGroup: "dw",
      url: "https://rss.dw.com/rdf/rss-en-all",
      siteUrl: "https://www.dw.com/en/top-stories/s-9097",
      allowedHosts: ["dw.com", "www.dw.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    // ---- BATCH A: TECHNOLOGY & SCIENCE ----
    {
      id: "techcrunch",
      name: "TechCrunch",
      publisher: "TechCrunch",
      authority: "TechCrunch",
      kind: "rss",
      categories: ["technology", "business", "ai"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "techcrunch",
      url: "https://techcrunch.com/feed/",
      siteUrl: "https://techcrunch.com/",
      allowedHosts: ["techcrunch.com"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "nasa-breaking",
      name: "NASA Breaking News",
      publisher: "NASA",
      authority: "National Aeronautics and Space Administration",
      kind: "rss",
      categories: ["science", "space"],
      region: "global",
      trustTier: 1,
      dependencyGroup: "nasa",
      url: "https://www.nasa.gov/rss/dyn/breaking_news.rss",
      siteUrl: "https://www.nasa.gov/news/",
      allowedHosts: ["nasa.gov", "www.nasa.gov"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    {
      id: "mit-news",
      name: "MIT News",
      publisher: "MIT",
      authority: "Massachusetts Institute of Technology",
      kind: "rss",
      categories: ["technology", "science", "ai", "education"],
      region: "global",
      trustTier: 1,
      dependencyGroup: "mit",
      url: "https://news.mit.edu/rss/feed",
      siteUrl: "https://news.mit.edu/",
      allowedHosts: ["news.mit.edu"],
      strictFilter: false,
      enabled: true,
      usage: "approved",
    },
    // ---- EXPANDED COVERAGE: VERIFIED PUBLIC RSS ENDPOINTS ----
    {
      id: "esa-space-news",
      name: "ESA Space News",
      publisher: "European Space Agency",
      authority: "European Space Agency official newsroom",
      kind: "rss",
      categories: ["space", "science"],
      region: "global",
      trustTier: 1,
      dependencyGroup: "esa",
      url: "https://www.esa.int/rssfeed/Our_Activities/Space_News",
      siteUrl: "https://www.esa.int/Newsroom",
      allowedHosts: ["www.esa.int", "esa.int"],
      strictFilter: false,
      feedSummaryPolicy: "bounded",
      enabled: true,
      usage: "approved",
    },
    {
      id: "un-climate-news",
      name: "UN Climate News",
      publisher: "UN News",
      authority: "United Nations official news service",
      kind: "rss",
      categories: ["environment", "world"],
      region: "global",
      trustTier: 1,
      dependencyGroup: "united-nations",
      url: "https://news.un.org/feed/subscribe/en/news/topic/climate-change/feed/rss.xml",
      siteUrl: "https://news.un.org/en/news/topic/climate-change",
      allowedHosts: ["news.un.org"],
      strictFilter: false,
      feedSummaryPolicy: "bounded",
      enabled: true,
      usage: "approved",
    },
    {
      id: "espn-top-news",
      name: "ESPN Top Sports News",
      publisher: "ESPN",
      authority: "ESPN sports newsroom",
      kind: "rss",
      categories: ["sports"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "espn",
      url: "https://www.espn.com/espn/rss/news",
      siteUrl: "https://www.espn.com/",
      allowedHosts: ["www.espn.com", "espn.com"],
      strictFilter: false,
      feedSummaryPolicy: "metadata-only",
      enabled: true,
      usage: "approved",
    },
    {
      id: "variety-entertainment",
      name: "Variety Entertainment",
      publisher: "Variety",
      authority: "Variety entertainment newsroom",
      kind: "rss",
      categories: ["entertainment"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "variety",
      url: "https://variety.com/feed/",
      siteUrl: "https://variety.com/",
      allowedHosts: ["variety.com", "www.variety.com"],
      strictFilter: false,
      feedSummaryPolicy: "metadata-only",
      enabled: true,
      usage: "approved",
    },
    {
      id: "nasdaq-markets",
      name: "Nasdaq Markets",
      publisher: "Nasdaq",
      authority: "Nasdaq market news and commentary",
      kind: "rss",
      categories: ["markets", "business"],
      region: "global",
      trustTier: 2,
      dependencyGroup: "nasdaq",
      url: "https://www.nasdaq.com/feed/rssoutbound?category=Markets",
      siteUrl: "https://www.nasdaq.com/market-activity",
      allowedHosts: ["www.nasdaq.com", "nasdaq.com"],
      strictFilter: false,
      feedSummaryPolicy: "metadata-only",
      enabled: true,
      usage: "approved",
    },
  ];
}
