"""initial trusted ingestion schema

Revision ID: cd82bdaef472
Revises: 
Create Date: 2026-07-22 19:30:40.088785
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd82bdaef472'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('allowed_redirect_hosts', sa.JSON(), nullable=False),
    sa.Column('trust_tier', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_response_bytes', sa.Integer(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('robots_mode', sa.String(length=24), nullable=False),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('permitted_use', sa.String(length=32), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_response_bytes > 0', name=op.f('ck_sources_positive_response_limit')),
    sa.CheckConstraint('poll_interval_seconds >= 300', name=op.f('ck_sources_poll_interval_minimum')),
    sa.CheckConstraint('trust_tier BETWEEN 1 AND 4', name=op.f('ck_sources_trust_tier_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_enabled'), 'sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('normalized_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('identity_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('content_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalizer_version', sa.String(length=100), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_normalized_documents_positive_revision')),
    sa.CheckConstraint('length(identity_hash) = 32', name=op.f('ck_normalized_documents_identity_hash_length')),
    sa.CheckConstraint('length(content_hash) = 32', name=op.f('ck_normalized_documents_content_hash_length')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_normalized_documents_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_documents')),
    sa.UniqueConstraint('source_id', 'identity_hash', 'content_hash', name='document_replay_identity'),
    sa.UniqueConstraint('source_id', 'identity_hash', 'revision', name='document_revision_identity')
    )
    op.create_index(op.f('ix_normalized_documents_content_hash'), 'normalized_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_normalized_documents_identity_hash'), 'normalized_documents', ['identity_hash'], unique=False)
    op.create_index(op.f('ix_normalized_documents_source_id'), 'normalized_documents', ['source_id'], unique=False)
    op.create_index('uq_current_document_revision', 'normalized_documents', ['source_id', 'identity_hash'], unique=True, postgresql_where=sa.text('superseded_at IS NULL'), sqlite_where=sa.text('superseded_at IS NULL'))
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('run_type', sa.String(length=24), nullable=False),
    sa.Column('trigger_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('collector_version', sa.String(length=100), nullable=True),
    sa.Column('normalizer_version', sa.String(length=100), nullable=True),
    sa.Column('counters', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_pipeline_runs_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('raw_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('canonical_url_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('sha256', sa.LargeBinary(length=32), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('byte_length', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=True),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('byte_length >= 0', name=op.f('ck_raw_artifacts_nonnegative_byte_length')),
    sa.CheckConstraint('byte_length = length(payload)', name=op.f('ck_raw_artifacts_payload_length_matches')),
    sa.CheckConstraint('length(sha256) = 32', name=op.f('ck_raw_artifacts_sha256_length')),
    sa.CheckConstraint('length(canonical_url_hash) = 32', name=op.f('ck_raw_artifacts_canonical_url_hash_length')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_artifacts_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_artifacts')),
    sa.UniqueConstraint('source_id', 'canonical_url_hash', 'sha256', name='artifact_identity')
    )
    op.create_index(op.f('ix_raw_artifacts_sha256'), 'raw_artifacts', ['sha256'], unique=False)
    op.create_index(op.f('ix_raw_artifacts_source_id'), 'raw_artifacts', ['source_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=24), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_audit_events_pipeline_run_id_pipeline_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_table('document_provenance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('raw_locator', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['raw_artifacts.id'], name=op.f('fk_document_provenance_artifact_id_raw_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['normalized_documents.id'], name=op.f('fk_document_provenance_document_id_normalized_documents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_provenance')),
    sa.UniqueConstraint('document_id', 'artifact_id', name='document_artifact_edge')
    )
    op.create_index(op.f('ix_document_provenance_artifact_id'), 'document_provenance', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_document_provenance_document_id'), 'document_provenance', ['document_id'], unique=False)
    op.create_table('source_fetches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_run_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('requested_url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_bytes', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=False),
    sa.Column('redirect_chain', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['raw_artifacts.id'], name=op.f('fk_source_fetches_artifact_id_raw_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_source_fetches_pipeline_run_id_pipeline_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_fetches_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_fetches'))
    )
    op.create_index(op.f('ix_source_fetches_pipeline_run_id'), 'source_fetches', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_source_fetches_source_id'), 'source_fetches', ['source_id'], unique=False)
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("""
        CREATE OR REPLACE FUNCTION reject_immutable_mutation() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION 'immutable table % cannot be changed', TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;
        """)
        op.execute("CREATE TRIGGER raw_artifacts_immutable BEFORE UPDATE OR DELETE ON raw_artifacts FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation()")
        op.execute("CREATE TRIGGER audit_events_immutable BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION reject_immutable_mutation()")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP TRIGGER IF EXISTS audit_events_immutable ON audit_events")
        op.execute("DROP TRIGGER IF EXISTS raw_artifacts_immutable ON raw_artifacts")
        op.execute("DROP FUNCTION IF EXISTS reject_immutable_mutation()")
    op.drop_index(op.f('ix_source_fetches_source_id'), table_name='source_fetches')
    op.drop_index(op.f('ix_source_fetches_pipeline_run_id'), table_name='source_fetches')
    op.drop_table('source_fetches')
    op.drop_index(op.f('ix_document_provenance_document_id'), table_name='document_provenance')
    op.drop_index(op.f('ix_document_provenance_artifact_id'), table_name='document_provenance')
    op.drop_table('document_provenance')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_raw_artifacts_source_id'), table_name='raw_artifacts')
    op.drop_index(op.f('ix_raw_artifacts_sha256'), table_name='raw_artifacts')
    op.drop_table('raw_artifacts')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_normalized_documents_source_id'), table_name='normalized_documents')
    op.drop_index('uq_current_document_revision', table_name='normalized_documents')
    op.drop_index(op.f('ix_normalized_documents_identity_hash'), table_name='normalized_documents')
    op.drop_index(op.f('ix_normalized_documents_content_hash'), table_name='normalized_documents')
    op.drop_table('normalized_documents')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_index(op.f('ix_sources_enabled'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
