"use client";
import { useMemo, useState } from "react";
import { Check, ChevronRight, RotateCcw, Play, Pause } from "lucide-react";
import type { AcademyProgress } from "../../../lib/courses/progress";
import { completeLesson, saveCourseProgress } from "../../../lib/courses/progress";
import { COURSE_PATH } from "../../../lib/courses/curriculum";
import type { Lesson } from "../../../lib/courses/types";

function Animation({ lesson }: { lesson: Lesson }) { const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const max = lesson.animation.steps.length - 1; return <div className="academy-animation"><div className="academy-flow">{lesson.animation.steps.map((label, index) => <div key={label} className={index === step ? "academy-node active" : "academy-node"}><span>{index + 1}</span>{label}{index < max && <ChevronRight size={16} />}</div>)}</div><div className="academy-controls"><button onClick={() => setPlaying(!playing)}>{playing ? <Pause size={15} /> : <Play size={15} />}{playing ? "Pause" : "Play"}</button><button onClick={() => setStep((value) => Math.max(0, value - 1))}>Back</button><button onClick={() => setStep((value) => Math.min(max, value + 1))}>Step</button><button onClick={() => setStep(0)}><RotateCcw size={14} />Replay</button></div><p className="academy-caution">{lesson.animation.caution}</p></div> }
function LessonView({ lesson, progress, onComplete, onBack }: { lesson: Lesson; progress: AcademyProgress; onComplete: (next: AcademyProgress) => void; onBack: () => void }) { const [choice, setChoice] = useState<string | null>(null); const [answer, setAnswer] = useState(""); const [submitted, setSubmitted] = useState(false); const question = lesson.quiz.questions[0]; const passed = choice === question.correctId; const exerciseCorrect = answer.trim().toLowerCase().includes(lesson.exercise.answer.toLowerCase()); return <section className="academy-page"><button className="text-button" onClick={onBack}>← Academy roadmap</button><span className="eyebrow">LESSON</span><h1>{lesson.title}</h1><p className="academy-lede">{lesson.summary}</p><div className="academy-card"><h2>Understand it</h2>{lesson.keyPoints.map((point) => <p key={point}>✓ {point}</p>)}</div><Animation lesson={lesson} /><div className="academy-card"><h2>Quick check</h2><p>{question.prompt}</p>{question.options.map((option) => <button key={option.id} className={choice === option.id ? "academy-option selected" : "academy-option"} onClick={() => setChoice(option.id)}>{option.label}</button>)}{choice && <p className={passed ? "academy-success" : "academy-error"}>{passed ? question.explanation : "Not quite — try again."}</p>}</div><div className="academy-card"><h2>Try it</h2><p>{lesson.exercise.prompt}</p><input value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Type your answer" /><button className="primary-button" onClick={() => setSubmitted(true)}>Check answer</button>{submitted && <p className={exerciseCorrect ? "academy-success" : "academy-error"}>{exerciseCorrect ? lesson.exercise.explanation : `Hint: ${lesson.exercise.answer}`}</p>}</div><button className="primary-button academy-complete" disabled={!passed || !exerciseCorrect} onClick={() => onComplete(completeLesson(progress, lesson, passed ? 1 : 0, exerciseCorrect))}>{progress.completedLessons[lesson.id] ? "Lesson completed" : "Complete lesson"}</button></section> }
export function AcademyView({ progress, onProgressChange }: { progress: AcademyProgress; onProgressChange: (progress: AcademyProgress) => void }) { const [lessonId, setLessonId] = useState(progress.currentLessonId); const lessons = useMemo(() => COURSE_PATH.tiers.flatMap((tier) => tier.modules.flatMap((module) => module.lessons)), []); const lesson = lessons.find((item) => item.id === lessonId); if (lesson) return <LessonView lesson={lesson} progress={progress} onBack={() => setLessonId(null)} onComplete={(next) => { saveCourseProgress(window.localStorage, next); onProgressChange(next); setLessonId(null); }} />; return <section className="academy-page"><span className="eyebrow">CYBER ACADEMY</span><h1>Learn how the internet really works.</h1><p className="academy-lede">Short lessons, interactive diagrams and practice — saved privately on this device.</p><div className="academy-streak">🔥 {progress.streak.count}-day learning streak</div>{COURSE_PATH.tiers.map((tier, tierIndex) => <div className="academy-tier" key={tier.id}><div><span className="eyebrow">TIER {tierIndex + 1}</span><h2>{tier.title}</h2><p>{tier.summary}</p></div>{tier.modules.map((module) => <div className="academy-module" key={module.id}><div><strong>{module.title}</strong><small>{module.summary}</small></div>{module.lessons.map((item) => { const done = Boolean(progress.completedLessons[item.id]); return <button key={item.id} className="academy-lesson" onClick={() => setLessonId(item.id)}><span className={done ? "academy-check done" : "academy-check"}>{done ? <Check size={15} /> : ""}</span><span>{item.title}<small>{item.summary}</small></span><ChevronRight size={17} /></button> })}</div>)}</div>)}<button className="text-button" onClick={() => { saveCourseProgress(window.localStorage, { completedLessons: {}, currentLessonId: null, streak: { lastVisitedDate: null, count: 0 } }); onProgressChange({ completedLessons: {}, currentLessonId: null, streak: { lastVisitedDate: null, count: 0 } }); }}>Reset progress</button></section> }
